frost-scroll test suite
juwara0/ember-frost-core pull request #18
Opened 2016-09-26 19:47 UTC by juwara0

Updated scroll component to also unregister the event handlers
Add unit and integration tests
Created README
Updated dummy app

2016-09-29 23:48 UTC, sglanzer-fire requested changes
Just need to examine the lifecycle hook used for the cleanup - otherwise 👍

2016-09-29 23:48 UTC, sglanzer commented on addon/components/frost-scroll.js
> +  willClearRender () {
This is called before every re-render, I think you want http://emberjs.com/api/classes/Ember.Component.html#event_willDestroyElement

2016-09-29 23:48 UTC, sglanzer commented on tests/integration/components/frost-scroll-test.js
> +    it('sets full class correctly', function () {
Not that I'm saying this hurts, but since we're not proxying the class this is essentially testing the ember component interface

2016-09-29 23:48 UTC, sglanzer commented on tests/unit/components/frost-scroll-test.js
> +    it('includes className frost-radio-button', function () {
`frost-radio-button` copy error

2016-09-30 13:31 UTC, juwara0 commented on tests/unit/components/frost-scroll-test.js
> +    it('includes className frost-radio-button', function () {
Done

2016-09-30 13:31 UTC, juwara0 commented on tests/integration/components/frost-scroll-test.js
> +    it('sets full class correctly', function () {
I agree. This is testing Ember. I have removed this test.

2016-09-30 13:33 UTC, juwara0 commented on addon/components/frost-scroll.js
> +  willClearRender () {
`willDestroyElement` is the hook I want. Thank you.

2016-09-30 14:00 UTC, merged